import { Theme, Layout } from './types';

export const THEMES: Theme[] = [
    {
        name: 'Nebula',
        background: 'bg-gradient-to-br from-slate-900 via-indigo-900 to-slate-900',
        textColor: 'text-slate-300',
        titleColor: 'text-white',
        bulletColor: 'text-indigo-400',
    },
    {
        name: 'Oceanic',
        background: 'bg-gradient-to-br from-blue-900 to-teal-800',
        textColor: 'text-blue-100',
        titleColor: 'text-white',
        bulletColor: 'text-teal-300',
    },
    {
        name: 'Professional',
        background: 'bg-white',
        textColor: 'text-gray-600',
        titleColor: 'text-gray-800',
        bulletColor: 'text-blue-600',
    },
    {
        name: 'Sunset',
        background: 'bg-gradient-to-br from-red-500 via-orange-600 to-yellow-500',
        textColor: 'text-white',
        titleColor: 'text-white font-bold',
        bulletColor: 'text-yellow-200',
    },
    {
        name: 'Emerald',
        background: 'bg-gradient-to-br from-emerald-800 to-gray-900',
        textColor: 'text-gray-200',
        titleColor: 'text-white',
        bulletColor: 'text-emerald-400',
    },
    {
        name: 'Ruby',
        background: 'bg-gradient-to-br from-red-800 via-rose-800 to-red-900',
        textColor: 'text-rose-100',
        titleColor: 'text-white',
        bulletColor: 'text-rose-300',
    },
    {
        name: 'Graphite',
        background: 'bg-gray-800',
        textColor: 'text-gray-300',
        titleColor: 'text-white',
        bulletColor: 'text-gray-400',
    },
    {
        name: 'Classic',
        background: 'bg-gray-100',
        textColor: 'text-gray-700',
        titleColor: 'text-black',
        bulletColor: 'text-gray-500',
    },
     {
        name: 'Vintage',
        background: 'bg-yellow-50',
        textColor: 'text-yellow-900',
        titleColor: 'text-black',
        bulletColor: 'text-yellow-800',
    },
    {
        name: 'Cyberpunk',
        background: 'bg-black',
        textColor: 'text-cyan-300',
        titleColor: 'text-fuchsia-500',
        bulletColor: 'text-cyan-400',
    },
    {
        name: 'Forest',
        background: 'bg-gradient-to-br from-green-900 via-lime-900 to-green-900',
        textColor: 'text-lime-100',
        titleColor: 'text-white',
        bulletColor: 'text-lime-400',
    },
    {
        name: 'Sky',
        background: 'bg-gradient-to-b from-sky-200 to-sky-400',
        textColor: 'text-sky-900',
        titleColor: 'text-white',
        bulletColor: 'text-sky-800',
    },
    {
        name: 'Royal',
        background: 'bg-gradient-to-br from-blue-900 to-indigo-900',
        textColor: 'text-indigo-200',
        titleColor: 'text-yellow-300',
        bulletColor: 'text-yellow-400',
    },
    {
        name: 'Crimson',
        background: 'bg-gradient-to-br from-red-900 to-black',
        textColor: 'text-red-200',
        titleColor: 'text-white',
        bulletColor: 'text-red-400',
    },
    {
        name: 'Pastel Dream',
        background: 'bg-gradient-to-br from-pink-200 via-purple-200 to-indigo-200',
        textColor: 'text-gray-700',
        titleColor: 'text-purple-800',
        bulletColor: 'text-purple-500',
    },
];

export const LAYOUTS: Layout[] = [
    {
        name: 'Image Right',
        className: 'grid grid-cols-2',
        imagePosition: 'right',
        imageClassName: 'h-full',
        textClassName: 'h-full',
    },
    {
        name: 'Image Left',
        className: 'grid grid-cols-2',
        imagePosition: 'left',
        imageClassName: 'h-full',
        textClassName: 'h-full',
    },
    {
        name: 'Image Top',
        className: 'flex flex-col',
        imagePosition: 'top',
        imageClassName: 'h-1/2',
        textClassName: 'h-1/2',
    },
    {
        name: 'Image Bottom',
        className: 'flex flex-col',
        imagePosition: 'bottom',
        imageClassName: 'h-1/2',
        textClassName: 'h-1/2',
    },
    {
        name: 'Text Overlay',
        className: 'relative',
        imagePosition: 'overlay-center',
        imageClassName: 'absolute inset-0',
        textClassName: 'relative z-10',
    },
    {
        name: 'Text Wide Left',
        className: 'grid grid-cols-3',
        imagePosition: 'right',
        imageClassName: 'col-span-1 h-full',
        textClassName: 'col-span-2 h-full',
    },
    {
        name: 'Text Wide Right',
        className: 'grid grid-cols-3',
        imagePosition: 'left',
        imageClassName: 'col-span-1 h-full',
        textClassName: 'col-span-2 h-full',
    },
    {
        name: 'Image Wide Left',
        className: 'grid grid-cols-3',
        imagePosition: 'left',
        imageClassName: 'col-span-2 h-full',
        textClassName: 'col-span-1 h-full',
    },
    {
        name: 'Image Wide Right',
        className: 'grid grid-cols-3',
        imagePosition: 'right',
        imageClassName: 'col-span-2 h-full',
        textClassName: 'col-span-1 h-full',
    },
    {
        name: 'Overlay Top',
        className: 'relative',
        imagePosition: 'overlay-top',
        imageClassName: 'absolute inset-0',
        textClassName: 'relative z-10 mb-auto',
    },
    {
        name: 'Overlay Bottom',
        className: 'relative',
        imagePosition: 'overlay-bottom',
        imageClassName: 'absolute inset-0',
        textClassName: 'relative z-10 mt-auto',
    },
    {
        name: 'Image Top Tall',
        className: 'flex flex-col',
        imagePosition: 'top',
        imageClassName: 'h-2/3',
        textClassName: 'h-1/3',
    },
    {
        name: 'Image Bottom Tall',
        className: 'flex flex-col',
        imagePosition: 'bottom',
        imageClassName: 'h-2/3',
        textClassName: 'h-1/3',
    },
];


export const DETAIL_LEVELS = ['Basic', 'Standard', 'Detailed'] as const;
export const PRESENTATION_STYLES = ['Professional', 'Conversational', 'Academic', 'Business', 'Casual', 'Technical'] as const;